log_level: debug 
log_dir: ./log
log_prefix: gateway
log_stderr: true 

rpc_addr: 127.0.0.1
rpc_port: 36002
health_port: 36003
rpc_server_name: gate

lis_client_addr: 0.0.0.0
lis_client_port: 36001

# 客户端监听地址，需要返回给客户端用以发起连接
lis_client_addr_inquire: 127.0.0.1

redis_addr: 127.0.0.1:6379
redis_passwd: 

consul_addr: 127.0.0.1:8500

nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161

pprofExposeType:
pprofHttpPort: 9909

node: 1

# 平台服地址
platform_http_address: http://localhost:8080