
#### service loader configs
# log 
log_level: debug 
log_dir: ./log
log_prefix: login 
log_stderr: true 

# redis 
redis_addr: 127.0.0.1:6379
redis_passwd: 

# nsq 
nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161

# consul 
consul_addr: 127.0.0.1:8500

rpc_addr: 127.0.0.1
rpc_port: 36201
rpc_server_name: login


# mysql 数据库列表
mysql_list:
  log:
    user: root
    passwd: 123456
    addr: 127.0.0.1:3306
    db: log 
    params:
      charset: utf8

node: 1
