#日志配置
log_level: debug
log_dir: ./log
log_prefix: back
log_stderr: true 

#RPC服务地址
# rpc_addr: 192.168.8.17
#RPC服务监听Port
# rpc_port: 36331
#RPC服务健康监控Port
# health_port: 36332
#RPC服务名
# rpc_server_name: gold
#路由方式
# rpc_lb: hash
#RPC服务组名
#group_name: 1000,1001


#consul 服务中心配置
consul_addr: 127.0.0.1:8500
redis_list:
  back:
#redis 配置
    addr: 127.0.0.1:6379
    passwd:

# mysql 数据库列表, db用户名和密码中不能带@符号
mysql_list:
  player:
    user: root
    passwd: 12345678
    addr: 192.168.7.108:3306
    db: steve
    params:
      charset: utf8
  log:
    user: root
    passwd: 12345678
    addr: 192.168.7.108:3306
    db: steve
    params:
      charset: utf8

# nsq 
nsqd_addr: 127.0.0.1:4150
nsqlookupd_addrs: 
  - 127.0.0.1:4161
